version: '3.0'
services:
  # react:
  #   container_name: react
  #   build:
  #     context: .
  #     dockerfile: ./frontend.dockerfile
  #   volumes:
  #     - ./frontend:/app
  #     - ./init:/init
  #   command: bash -c "tail -f /init/dummy.txt"
  #   ports:
  #     - "3000:3000"

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend.dockerfile
    depends_on:
      sqldatabase:
        condition: service_healthy
    volumes:
      - ./backend:/base
      - ./init:/init
    command: bash -c "supervisord && sleep 5s && tail -f /var/log/supervisor/uwsgi-stdout.log"
    ports:
      - "9000:80"

  sqldatabase:
    container_name: db
    image: mysql:5.7
    restart: always
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 1s
      retries: 24
    environment:
      MYSQL_USER: local
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: local123
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: icecream
    ports:
      - "3306:3306"
